apiVersion: v1
kind: ConfigMap
metadata:
  name: ks-scheduler-config
  namespace: kube-system
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: ks-scheduler
    algorithmSource:
      policy:
        {
          "kind" : "Policy",
          "apiVersion" : "v1",
          "predicates" : [
            {"name" : "PodFitsHostPorts"},
            {"name" : "PodFitsResources"},
            {"name" : "NoDiskConflict"},
            {"name" : "MatchNodeSelector"},
          ],
          "priorities" : [
            {"name" : "LeastRequestedPriority", "weight" : 1},
            {"name" : "BalancedResourceAllocation", "weight" : 1},
            {"name" : "ImageLocalityPriority", "weight" : 1.5}
          ],
          "extenders" : [{
             "urlPrefix": "http://localhost:8080/scheduler",
             "filterVerb": "/predicates/alwaystrue",
             "prioritizeVerb": "/priorities/pipeline",
             "weight": 3,
             "enableHttps": false,
             "nodeCacheCapable": false
          }],
          "hardPodAffinitySymmetricWeight" : 10
        }
    leaderElection:
      leaderElect: false
      lockObjectName: ks-scheduler
      lockObjectNamespace: kube-system
#---
# LeastRequestedPriority: (0-10) cpu((capacity – sum(requested)) * 10 / capacity) + memory((capacity – sum(requested)) * 10 / capacity) / 2
# BalancedResourceAllocation: (0-10) 10-abs((c_re/c_capacity+m_re/m_capacity)*10)
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: ks-scheduler-policy
#  namespace: kube-system
#data:
#  policy.cfg: |
#    {
#      "kind" : "Policy",
#      "apiVersion" : "v1",
#      "predicates" : [
#        {"name" : "PodFitsHostPorts"},
#        {"name" : "PodFitsResources"},
#        {"name" : "NoDiskConflict"},
#        {"name" : "MatchNodeSelector"},
#      ],
#      "priorities" : [
#        {"name" : "LeastRequestedPriority", "weight" : 1},
#        {"name" : "BalancedResourceAllocation", "weight" : 1},
#        {"name" : "ImageLocalityPriority", "weight" : 1.5}
#      ],
#      "extenders" : [{
#        "urlPrefix": "http://localhost:8080/scheduler",
#        "filterVerb": "/priorities/alwaystrue",
#        "prioritizeVerb": "/priorities/pipeline",
#        "weight": 3,
#        "enableHttps": false,
#        "nodeCacheCapable": false
#      }],
#      "hardPodAffinitySymmetricWeight" : 10
#    }