apiVersion: v1
kind: ServiceAccount
metadata:
  name: ks-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ks-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: ks-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-scheduler
  namespace: kube-system
  labels:
    app: ks-scheduler
    version: advanced-2.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-scheduler
      version: advanced-2.1.0
  template:
    metadata:
      labels:
        app: ks-scheduler
        version: advanced-2.1.0
    spec:
      serviceAccountName: ks-scheduler
      nodeSelector:
        role: master
      volumes:
      - hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: FileOrCreate
        name: kubeconfig
      - name: ks-scheduler-config
        configMap:
          name: ks-scheduler-config
      containers:
        - name: ks-scheduler
          image: dockerhub.qingcloud.com/google_containers/hyperkube:v1.13.5
          imagePullPolicy: IfNotPresent
          args:
            - kube-scheduler
            - --address=0.0.0.0
            - --scheduler-name=ks-scheduler
            - --feature-gates=KubeletPluginsWatcher=false,CSINodeInfo=false,CSIDriverRegistry=false,RotateKubeletClientCertificate=true
            - --kubeconfig=/etc/kubernetes/scheduler.conf
            - --leader-elect=false
            - --config=/ks-scheduler/config.yaml
          volumeMounts:
          - mountPath: /etc/kubernetes/scheduler.conf
            name: kubeconfig
            readOnly: true
          - name: ks-scheduler-config
            mountPath: /ks-scheduler
        - name: ks-scheduler-pipeline
          image: zhuxiaoyang/ks-pipeline-scheduler:alpine
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
          readinessProbe:
            httpGet:
              path: /version
              port: 8080
          ports:
            - containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: ks-pipeline-scheduler
#    version: advanced-2.1.0
#  name: ks-pipeline-scheduler
#  namespace: kube-system
#spec:
#  ports:
#    - port: 8080
#      protocol: TCP
#      targetPort: 8080
#  selector:
#    app: ks-pipeline-scheduler
#    version: advanced-2.1.0
#  sessionAffinity: None
#  type: ClusterIP