apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-scheduler
  namespace: kube-system
  labels:
    app: ks-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-scheduler
  template:
    metadata:
      labels:
        app: ks-scheduler
    spec:
      volumes:
      - name: ks-scheduler-config
        configMap:
          name: ks-scheduler-config
      containers:
      - name: ks-scheduler-default
        image: dockerhub.qingcloud.com/google_containers/hyperkube:v1.13.5
        imagePullPolicy: IfNotPresent
        args:
        - kube-scheduler
        - --config=/ks-scheduler/config.yaml
        - -v=4
        volumeMounts:
        - name: ks-scheduler-config
          mountPath: /ks-scheduler
      - name: ks-scheduler-extender
        image: a/b:c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /version
            port: 80
        readinessProbe:
          httpGet:
            path: /version
            port: 80
        ports:
          - containerPort: 80