apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-scheduler-1
  namespace: kube-system
  labels:
    app: ks-scheduler
    version: advanced-2.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-scheduler
      version: advanced-2.1.0
  template:
    metadata:
      labels:
        app: ks-scheduler
        version: advanced-2.1.0
    spec:
      containers:
        - name: ks-scheduler-pipeline
          image: zhuxiaoyang/ks-pipeline-scheduler:alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
          readinessProbe:
            httpGet:
              path: /version
              port: 8080
          ports:
            - containerPort: 8080