apiVersion: apps/v1
kind: Deployment
metadata:
  name: ks-scheduler
  namespace: kube-system
  labels:
    app: ks-scheduler
    version: advanced-2.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-scheduler
      version: advanced-2.1.0
  template:
    metadata:
      labels:
        app: ks-scheduler
        version: advanced-2.1.0
    spec:
      serviceAccountName: ks-scheduler
      nodeSelector:
        role: master
      volumes:
        - hostPath:
            path: /etc/kubernetes/scheduler.conf
            type: FileOrCreate
          name: kubeconfig
        - name: ks-config
          hostPath:
            path: /root/config.yaml
      containers:
        - command:
            - kube-scheduler
            - --address=0.0.0.0
            - --feature-gates=KubeletPluginsWatcher=false,CSINodeInfo=false,CSIDriverRegistry=false,RotateKubeletClientCertificate=true
            - --kubeconfig=/etc/kubernetes/scheduler.conf
            - --leader-elect=true
            - --config=/ks-scheduler/config.yaml
          name: ks-scheduler
          image: dockerhub.qingcloud.com/google_containers/hyperkube:v1.13.5
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/kubernetes/scheduler.conf
              name: kubeconfig
              readOnly: true
            - name: ks-config
              mountPath: /ks-scheduler/config.yaml
        - name: ks-scheduler-pipeline
          image: zhuxiaoyang/ks-pipeline-scheduler:alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /version
              port: 8080
          readinessProbe:
            httpGet:
              path: /version
              port: 8080
          ports:
            - containerPort: 8080